import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static List<Integer> removeEven(List<Integer> numbers) {
        if(null == numbers) {
            throw new IllegalArgumentException("");
        }

        return numbers
                .stream()
                .filter((Integer theNumber)-> theNumber % 2 != 0)
                .collect(Collectors.toList());
    }
}
