import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collector;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static List<Integer> removeEven(List<Integer> numbers) {
        if(null == numbers) {
            throw new IllegalArgumentException("");
        }

        return numbers
                .stream()
                .filter((Integer theNumber)-> theNumber % 2 != 0)
                .collect(Collectors.toList());
    }

    public static List<String> removeSwiftFox(List<String> foxType) {
        if(null == foxType) {
            throw new IllegalArgumentException();
        }

        return foxType
                .stream()
                .filter((String fox)-> !fox.equals("Swift Fox"))
                .collect(Collectors.toList());
    }

    public static List<Person> removeMinors(List<Person> persons) {
        if (null == persons) {
            throw new IllegalArgumentException();
        }
        return persons
                .stream()
                .filter((Person thePerson)-> thePerson.getAge() > 17)
                .collect(Collectors.toList());
    }
}
