/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test (expected = IllegalArgumentException.class)
    public void removeEvenShouldThrowsExceptionWhenNull() {
        Library.removeEven(null);
    }

    @Test
    public void removeEvenReturnsEmptyList() {
        List<Integer> result = Library.removeEven(Collections.emptyList());

        assertTrue(result.isEmpty());
    }

    @Test
    public void removeEvenReturnsAListOfAnOddNumberWhenGivenAnOdd() {
        List<Integer> result = Library.removeEven(Arrays.asList(1));

        assertEquals(Arrays.asList(1), result);
    }

    @Test
    public void removeEvenReturnsEmptyListWhenGivenOneEven() {
        List<Integer> result = Library.removeEven(Arrays.asList(2));

        assertEquals(Collections.emptyList(), result);
    }
}
